//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIA_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public int collectionId { get; set; }
        public string collectionTitle { get; set; }
        public string description { get; set; }
        public int collectibleCount { get; set; }
    }
}
